### ISSUE TITLE
[SUGGESTION] Fix folder structure for this project

### ISSUE THREAD

**Issue by JamesStGermain** [Discord-Coding-Community/FFXIV-Macros#1]
Not so much a macro, but there are no templates for general improvements to the project. 

I would suggest revisiting the folder structure of the project, as it doesn't quite follow the current class allocations. For instance, there are no folders for Paladins, or Red Mages, etc. 

Regardless of if there are macros for those folders or not, there should still be folders to encapsulate them when they inevitably arive.

Just a quality of life fix that will help you down the line for sure <3

**Comment by PhantomNimbi** [comment]
Done and done 

Should be somewhat more up to date now. Used the ingame Character menu to figure out what went where
